identity:
  - 7TWEw9qQxsc8w4WhPAX6zjZ8vuNBdtP21zUVN8K26RkD
  - A3k4tMWHgZ8GNDxckrGBkyn4RRZxhXsRoPqg7uSnAn38
  - EQ4mjyw9dGkLqfqHisy7BGfQHdr5JeCZ3chwoBUJorMx

settings:
  bot_api_key: "1703:AA-BB_CC"
  alarm_chat_id: "-2109"
  log_chat_id: "-9012"
